export const PAKISTAN_LOCATIONS = {
  Karachi: [
    'DHA Phase 1',
    'DHA Phase 2',
    'DHA Phase 4',
    'DHA Phase 5',
    'DHA Phase 6',
    'DHA Phase 7',
    'DHA Phase 8',
    'Bahria Town Karachi',
    'Clifton',
    'Gulshan-e-Iqbal',
    'Gulistan-e-Jauhar',
    'North Nazimabad',
    'Malir Cantt',
    'PECHS',
    'Scheme 33',
    'KDA Scheme 1',
    'Federal B Area',
    'Nazimabad',
    'Bath Island',
    'Navy Housing Scheme',
  ],
  Lahore: [
    'DHA Phase 1',
    'DHA Phase 2',
    'DHA Phase 3',
    'DHA Phase 4',
    'DHA Phase 5',
    'DHA Phase 6',
    'DHA Phase 7',
    'DHA Phase 8',
    'DHA Phase 9 (Prism)',
    'Bahria Town',
    'Gulberg',
    'Model Town',
    'Johar Town',
    'Lahore Cantt',
    'Lake City',
    'Wapda Town',
    'Askari 10',
    'Askari 11',
    'New Lahore City',
    'Valancia Town',
    'Faisal Town',
    'State Life Housing Society',
  ],
  Islamabad: [
    'DHA Phase 1',
    'DHA Phase 2',
    'DHA Phase 3',
    'DHA Phase 4',
    'DHA Phase 5',
    'Bahria Town (Phase 1-8)',
    'Sector F-6',
    'Sector F-7',
    'Sector F-8',
    'Sector F-10',
    'Sector F-11',
    'Sector E-7',
    'Sector E-11',
    'Sector G-11',
    'Sector G-13',
    'Sector G-14',
    'Sector I-8',
    'B-17 Multi Gardens',
    'Gulberg Greens',
    'Park View City',
    'Top City-1',
    'Mumtaz City',
  ],
  Rawalpindi: [
    'Bahria Town',
    'DHA Islamabad-Rawalpindi',
    'Satellite Town',
    'Chaklala Scheme 3',
    'Rawalpindi Cantt',
    'Adyala Road',
    'Peshawar Road',
    'Westridge',
    'Gulraiz Housing Scheme',
    'Askari 14',
  ],
  Faisalabad: [
    'Madina Town',
    'Peoples Colony 1',
    'Peoples Colony 2',
    'Kohinoor City',
    'Canal Road',
    'Citi Housing',
    'Wapda City',
    'FDA City',
    'Susan Road',
    'D Ground',
  ],
  Peshawar: [
    'Hayatabad',
    'DHA Peshawar',
    'University Town',
    'Regi Model Town',
    'Warsak Road',
    'Peshawar Cantt',
    'Dalazak Road',
  ],
  Multan: [
    'DHA Multan',
    'Multan Cantt',
    'Bosan Road',
    'Royal Orchard',
    'Wapda Town',
    'Model Town',
    'Gulgasht Colony',
  ],
  Gwadar: [
    'New Gwadar',
    'Sangar Housing Project',
    'Marine Drive',
    'Maanbar',
    'Golden Palms',
  ],
};

export const CITIES = Object.keys(PAKISTAN_LOCATIONS);
