import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../api/axios';

const statusColors = { available: 'bg-teal-50 text-teal-600', pending_approval: 'bg-gold-400/20 text-gold-500', rejected: 'bg-brand-50 text-brand-500', sold: 'bg-sand-100 text-sand-600', rented: 'bg-sand-100 text-sand-600' };
const MyListings = () => {
  const [properties, setProperties] = useState([]); const [loading, setLoading] = useState(true);
  useEffect(() => { const fetchMine = async () => { try { const { data } = await api.get('/properties/mine'); setProperties(data.properties); } catch (err) { /* ignore for now */ } finally { setLoading(false); } }; fetchMine(); }, []);
  const handleDelete = async (id) => { if (!confirm('Delete this listing?')) return; try { await api.delete(`/properties/${id}`); setProperties((prev) => prev.filter((p) => p._id !== id)); } catch (err) { alert(err.response?.data?.message || 'Failed to delete'); } };
  if (loading) return <p className="py-20 text-center text-sand-600">Loading...</p>;
  return <main className="mx-auto max-w-5xl px-4 py-8"><div className="mb-7 flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-500">Your portfolio</p><h1 className="section-heading mt-1">My Listings</h1></div><Link to="/post-property" className="btn-primary shrink-0 text-center">+ Post New Property</Link></div>{properties.length === 0 ? <div className="border border-dashed border-sand-400 bg-sand-100/60 px-6 py-14 text-center"><p className="font-display text-2xl font-semibold text-ink">Your first listing begins here.</p><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-sand-600">Show buyers what makes a property special, from its location to the details that make it feel like home.</p><Link to="/post-property" className="btn-primary mt-6 inline-block">Post a Property</Link></div> : <div className="space-y-3">{properties.map((p) => <div key={p._id} className="flex flex-col gap-4 border-l-4 border-sand-200 bg-white p-5 shadow-[0_8px_22px_rgba(43,36,32,0.04)] sm:flex-row sm:items-center sm:justify-between"><div><Link to={`/property/${p._id}`} className="font-display text-lg font-semibold text-ink hover:text-brand-500">{p.title}</Link><p className="mt-1 text-sm text-sand-600">{p.area}, {p.city} · PKR {p.price.toLocaleString()}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-semibold capitalize ${statusColors[p.status] || 'bg-sand-100 text-sand-600'}`}>{p.status.replace('_', ' ')}</span><button onClick={() => handleDelete(p._id)} className="text-sm font-medium text-brand-500 hover:text-brand-700 hover:underline">Delete</button></div></div>)}</div>}</main>;
};
export default MyListings;
