import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import api from '../api/axios';
import ImageUpload from '../components/ImageUpload';

const initialState = { title: '', description: '', listingType: 'buy', category: 'house', price: '', priceUnit: 'month', city: '', area: '', address: '', bedrooms: '', bathrooms: '', floors: '', areaSize: '', areaUnit: 'sqft', plotType: 'residential', amenitiesText: '', images: [] };
const Section = ({ title, children }) => <section className="border-t border-sand-200 pt-6"><h2 className="font-display text-xl font-semibold text-ink">{title}</h2><div className="mt-4 space-y-4">{children}</div></section>;
const Field = ({ label, children }) => <div><label className="mb-1.5 block text-sm font-medium text-ink">{label}</label>{children}</div>;

const PostProperty = () => {
  const navigate = useNavigate(); const { id } = useParams(); const [form, setForm] = useState(initialState); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [loading, setLoading] = useState(false); const [loadingListing, setLoadingListing] = useState(Boolean(id));
  const handleChange = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  useEffect(() => { if (!id) return; const load = async () => { try { const { data } = await api.get(`/properties/${id}`); const property = data.property; setForm({ ...initialState, ...property, images: property.images || [], amenitiesText: (property.amenities || []).join(', ') }); } catch (err) { setError(err.response?.data?.message || 'Unable to load this listing for editing.'); } finally { setLoadingListing(false); } }; load(); }, [id]);
  const handleSubmit = async (event, isDraft = false) => { event.preventDefault(); setError(''); setSuccess(''); setLoading(true); try { const payload = { ...form, isDraft, price: Number(form.price), areaSize: Number(form.areaSize), bedrooms: form.bedrooms ? Number(form.bedrooms) : undefined, bathrooms: form.bathrooms ? Number(form.bathrooms) : undefined, floors: form.floors ? Number(form.floors) : undefined, amenities: form.amenitiesText.split(',').map((amenity) => amenity.trim()).filter(Boolean) }; delete payload.amenitiesText; if (id) await api.put(`/properties/${id}`, payload); else await api.post('/properties', payload); setSuccess(isDraft ? 'Draft saved.' : id ? 'Listing updated and sent for review.' : 'Listing submitted! It will appear publicly once an admin approves it.'); setTimeout(() => navigate('/my-listings'), 1000); } catch (err) { setError(err.response?.data?.message || `Failed to ${id ? 'update' : 'create'} listing`); } finally { setLoading(false); } };
  if (loadingListing) return <p className="py-20 text-center text-sand-600">Loading your listing…</p>;
  return <main className="mx-auto max-w-2xl px-4 py-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-500">{id ? 'Refine your listing' : 'Create a listing'}</p><h1 className="section-heading mt-1">{id ? 'Edit Property' : 'Post a Property'}</h1><p className="mt-2 text-sm text-sand-600">Give buyers a clear, considered picture of the property.</p><form onSubmit={handleSubmit} className="mt-7 space-y-7 border border-sand-200 bg-white p-5 sm:p-7">{error && <p className="rounded-md bg-brand-50 px-3 py-2 text-sm text-brand-700">{error}</p>}{success && <p className="rounded-md bg-teal-50 px-3 py-2 text-sm text-teal-600">{success}</p>}
    <Section title="Basic Info"><Field label="Title"><input name="title" required value={form.title} onChange={handleChange} placeholder="e.g. Beautiful 3 Bedroom House in DHA" className="form-input" /></Field><Field label="Description"><textarea name="description" required rows={4} value={form.description} onChange={handleChange} className="form-input resize-y" /></Field><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field label="Listing Type"><select name="listingType" value={form.listingType} onChange={handleChange} className="form-input"><option value="buy">Buy (Sell)</option><option value="rent">Rent</option></select></Field><Field label="Category"><select name="category" value={form.category} onChange={handleChange} className="form-input"><option value="house">House</option><option value="apartment">Apartment</option><option value="plot">Plot</option></select></Field></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field label="Price (PKR)"><input type="number" name="price" required value={form.price} onChange={handleChange} className="form-input" /></Field>{form.listingType === 'rent' && <Field label="Per"><select name="priceUnit" value={form.priceUnit} onChange={handleChange} className="form-input"><option value="month">Month</option><option value="year">Year</option></select></Field>}</div></Section>
    <Section title="Location"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field label="City"><input name="city" required value={form.city} onChange={handleChange} className="form-input" /></Field><Field label="Area / Neighborhood"><input name="area" required value={form.area} onChange={handleChange} className="form-input" /></Field></div><Field label="Full Address (optional)"><input name="address" value={form.address} onChange={handleChange} className="form-input" /></Field></Section>
    <Section title="Property Details">{form.category !== 'plot' ? <div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><Field label="Bedrooms"><input type="number" name="bedrooms" value={form.bedrooms} onChange={handleChange} className="form-input" /></Field><Field label="Bathrooms"><input type="number" name="bathrooms" value={form.bathrooms} onChange={handleChange} className="form-input" /></Field><Field label="Floors"><input type="number" name="floors" value={form.floors} onChange={handleChange} className="form-input" /></Field></div> : <Field label="Plot Type"><select name="plotType" value={form.plotType} onChange={handleChange} className="form-input"><option value="residential">Residential</option><option value="commercial">Commercial</option><option value="agricultural">Agricultural</option></select></Field>}<div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field label="Area Size"><input type="number" name="areaSize" required value={form.areaSize} onChange={handleChange} className="form-input" /></Field><Field label="Unit"><select name="areaUnit" value={form.areaUnit} onChange={handleChange} className="form-input"><option value="sqft">Sq Ft</option><option value="sqyd">Sq Yard</option><option value="marla">Marla</option><option value="kanal">Kanal</option></select></Field></div></Section>
    <Section title="Photos & Amenities"><ImageUpload images={form.images} onChange={(images) => setForm({ ...form, images })} /><Field label="Amenities (comma separated)"><input name="amenitiesText" placeholder="Parking, Gas, Electricity, Security" value={form.amenitiesText} onChange={handleChange} className="form-input" /></Field></Section>
    <div className="flex flex-col-reverse gap-3 sm:flex-row"><button type="button" formNoValidate disabled={loading} onClick={(event) => handleSubmit(event, true)} className="btn-secondary flex-1">Save Draft</button><button type="submit" disabled={loading} className="btn-primary flex-1">{loading ? 'Saving...' : id ? 'Save & Submit for Review' : 'Submit Listing for Review'}</button></div>
  </form></main>;
};
export default PostProperty;
