import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../api/axios';
const initialState = { title: '', description: '', listingType: 'buy', category: 'house', price: '', priceUnit: 'month', city: '', area: '', address: '', bedrooms: '', bathrooms: '', floors: '', areaSize: '', areaUnit: 'sqft', plotType: 'residential', amenitiesText: '' };
const Section = ({ title, children }) => <section className="border-t border-sand-200 pt-6"><h2 className="font-display text-xl font-semibold text-ink">{title}</h2><div className="mt-4 space-y-4">{children}</div></section>;
const PostProperty = () => {
  const navigate = useNavigate(); const [form, setForm] = useState(initialState); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [loading, setLoading] = useState(false);
  const handleChange = (e) => setForm({ ...form, [e.target.name]: e.target.value });
  const handleSubmit = async (e) => { e.preventDefault(); setError(''); setSuccess(''); setLoading(true); try { const payload = { ...form, price: Number(form.price), areaSize: Number(form.areaSize), bedrooms: form.bedrooms ? Number(form.bedrooms) : undefined, bathrooms: form.bathrooms ? Number(form.bathrooms) : undefined, floors: form.floors ? Number(form.floors) : undefined, amenities: form.amenitiesText.split(',').map((a) => a.trim()).filter(Boolean) }; delete payload.amenitiesText; await api.post('/properties', payload); setSuccess('Listing submitted! It will appear publicly once an admin approves it.'); setForm(initialState); setTimeout(() => navigate('/my-listings'), 1500); } catch (err) { setError(err.response?.data?.message || 'Failed to create listing'); } finally { setLoading(false); } };
  return <main className="mx-auto max-w-2xl px-4 py-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-500">Create a listing</p><h1 className="section-heading mt-1">Post a Property</h1><p className="mt-2 text-sm text-sand-600">Give buyers a clear, considered picture of the property.</p><form onSubmit={handleSubmit} className="mt-7 space-y-7 border border-sand-200 bg-white p-5 sm:p-7">{error && <p className="rounded-md bg-brand-50 px-3 py-2 text-sm text-brand-700">{error}</p>}{success && <p className="rounded-md bg-teal-50 px-3 py-2 text-sm text-teal-600">{success}</p>}
    <Section title="Basic Info"><div><label className="mb-1.5 block text-sm font-medium text-ink">Title</label><input name="title" required value={form.title} onChange={handleChange} placeholder="e.g. Beautiful 3 Bedroom House in DHA" className="form-input" /></div><div><label className="mb-1.5 block text-sm font-medium text-ink">Description</label><textarea name="description" required rows={4} value={form.description} onChange={handleChange} className="form-input resize-y" /></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div><label className="mb-1.5 block text-sm font-medium text-ink">Listing Type</label><select name="listingType" value={form.listingType} onChange={handleChange} className="form-input"><option value="buy">Buy (Sell)</option><option value="rent">Rent</option></select></div><div><label className="mb-1.5 block text-sm font-medium text-ink">Category</label><select name="category" value={form.category} onChange={handleChange} className="form-input"><option value="house">House</option><option value="apartment">Apartment</option><option value="plot">Plot</option></select></div></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div><label className="mb-1.5 block text-sm font-medium text-ink">Price (PKR)</label><input type="number" name="price" required value={form.price} onChange={handleChange} className="form-input" /></div>{form.listingType === 'rent' && <div><label className="mb-1.5 block text-sm font-medium text-ink">Per</label><select name="priceUnit" value={form.priceUnit} onChange={handleChange} className="form-input"><option value="month">Month</option><option value="year">Year</option></select></div>}</div></Section>
    <Section title="Location"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div><label className="mb-1.5 block text-sm font-medium text-ink">City</label><input name="city" required value={form.city} onChange={handleChange} className="form-input" /></div><div><label className="mb-1.5 block text-sm font-medium text-ink">Area / Neighborhood</label><input name="area" required value={form.area} onChange={handleChange} className="form-input" /></div></div><div><label className="mb-1.5 block text-sm font-medium text-ink">Full Address (optional)</label><input name="address" value={form.address} onChange={handleChange} className="form-input" /></div></Section>
    <Section title="Property Details">{form.category !== 'plot' ? <div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><div><label className="mb-1.5 block text-sm font-medium text-ink">Bedrooms</label><input type="number" name="bedrooms" value={form.bedrooms} onChange={handleChange} className="form-input" /></div><div><label className="mb-1.5 block text-sm font-medium text-ink">Bathrooms</label><input type="number" name="bathrooms" value={form.bathrooms} onChange={handleChange} className="form-input" /></div><div><label className="mb-1.5 block text-sm font-medium text-ink">Floors</label><input type="number" name="floors" value={form.floors} onChange={handleChange} className="form-input" /></div></div> : <div><label className="mb-1.5 block text-sm font-medium text-ink">Plot Type</label><select name="plotType" value={form.plotType} onChange={handleChange} className="form-input"><option value="residential">Residential</option><option value="commercial">Commercial</option><option value="agricultural">Agricultural</option></select></div>}<div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div><label className="mb-1.5 block text-sm font-medium text-ink">Area Size</label><input type="number" name="areaSize" required value={form.areaSize} onChange={handleChange} className="form-input" /></div><div><label className="mb-1.5 block text-sm font-medium text-ink">Unit</label><select name="areaUnit" value={form.areaUnit} onChange={handleChange} className="form-input"><option value="sqft">Sq Ft</option><option value="sqyd">Sq Yard</option><option value="marla">Marla</option><option value="kanal">Kanal</option></select></div></div></Section>
    <Section title="Photos & Amenities"><div><label className="mb-1.5 block text-sm font-medium text-ink">Amenities (comma separated)</label><input name="amenitiesText" placeholder="Parking, Gas, Electricity, Security" value={form.amenitiesText} onChange={handleChange} className="form-input" /></div><p className="text-xs leading-5 text-sand-600">Note: image upload isn't wired into this form yet — you can add image URLs later via the edit endpoint once Cloudinary is fully connected.</p></Section>
    <button type="submit" disabled={loading} className="btn-primary w-full">{loading ? 'Submitting...' : 'Submit Listing for Review'}</button>
  </form></main>;
};
export default PostProperty;
