import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

const Signup = () => {
  const { register } = useAuth(); const navigate = useNavigate();
  const [form, setForm] = useState({ name: '', email: '', password: '', phone: '', role: 'buyer' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const handleSubmit = async (e) => { e.preventDefault(); setError(''); setLoading(true); try { await register(form); navigate('/'); } catch (err) { setError(err.response?.data?.message || 'Signup failed'); } finally { setLoading(false); } };
  return <main className="mx-auto grid min-h-[calc(100vh-4rem)] max-w-7xl lg:grid-cols-2">
    <aside className="relative overflow-hidden bg-brand-600 px-7 py-12 text-paper sm:px-12 lg:flex lg:items-end lg:px-16 lg:py-20"><div className="tile-pattern absolute inset-0 opacity-25" /><div className="relative max-w-lg"><span className="mb-6 block h-px w-16 bg-gold-400" /><p className="text-xs font-semibold uppercase tracking-[0.24em] text-gold-400">Start your search</p><h1 className="mt-4 font-display text-4xl font-semibold leading-tight sm:text-5xl">Find the place that holds your story.</h1><p className="mt-5 max-w-sm text-sm leading-6 text-brand-50">Join a marketplace designed around real homes, real neighbourhoods, and better informed decisions.</p></div></aside>
    <section className="flex items-center justify-center px-5 py-12 sm:px-10 lg:px-16 xl:px-24"><div className="w-full max-w-md"><p className="mb-3 text-xs font-semibold uppercase tracking-[0.2em] text-teal-500">Create your account</p><h2 className="font-display text-4xl font-semibold leading-tight text-ink">Your property journey starts here.</h2><form onSubmit={handleSubmit} className="mt-7 border-t border-sand-200 pt-6">{error && <p className="mb-4 rounded-md border border-brand-400/30 bg-brand-50 px-3 py-2 text-sm text-brand-700">{error}</p>}<div className="space-y-4"><div><label className="mb-1.5 block text-sm font-medium text-ink">Full Name</label><input type="text" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="form-input" /></div><div><label className="mb-1.5 block text-sm font-medium text-ink">Email</label><input type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="form-input" /></div><div><label className="mb-1.5 block text-sm font-medium text-ink">Phone</label><input type="tel" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} className="form-input" /></div><div><label className="mb-1.5 block text-sm font-medium text-ink">Password</label><input type="password" required minLength={6} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="form-input" /></div><div><label className="mb-1.5 block text-sm font-medium text-ink">I am a...</label><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} className="form-input"><option value="buyer">Buyer / Renter</option><option value="seller">Seller (I want to list my own property)</option><option value="agent">Agent (I sell properties for clients)</option></select></div></div><button type="submit" disabled={loading} className="btn-primary mt-6 w-full">{loading ? 'Creating account...' : 'Create Account'}</button><p className="mt-5 text-center text-sm text-sand-600">Already have an account? <Link to="/login" className="font-semibold text-teal-600 hover:text-teal-500 hover:underline">Log in</Link></p></form></div></section>
  </main>;
};
export default Signup;
